spring:
  application:
    name: url-shortener

  datasource:
    url: jdbc:postgresql://database-1.cuz8wa2so286.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: p92!eLV>9xG|aI6xG0(qI1t0YFDC

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 80
